print(True & True)
print(True & False)
print(False & False)
print("------------------")
print(True | True)
print(True | False)
print(False | False)
print("------------------")
print(not True)
print(not False)